name: naveeka
description: Naveeka - All-in-One Travel App with Inspiration, Planning, Booking, Chat, and AI Copilot in One Flow.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization (optional)
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # HTTP & Networking
  dio: ^5.5.0
  pretty_dio_logger: ^1.4.0
  http: ^1.2.2
  http_parser: ^4.0.2
  web_socket_channel: ^3.0.3

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Local storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Images
  cached_network_image: ^3.3.1

  # Animations
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

  # Media
  just_audio: ^0.9.39
  audio_waveforms: ^1.0.6

  # Lottie
  lottie: ^3.1.2

  # Routing
  go_router: ^13.2.0

  # Utils
  intl: ^0.20.2
  collection: ^1.18.0
  meta: ^1.12.0

  # Icons
  cupertino_icons: ^1.0.8

  # Charts
  fl_chart: ^0.68.0

  # Markdown
  flutter_markdown: ^0.7.3+1

  # Maps & Location
  google_maps_flutter: ^2.7.0
  geolocator: ^11.0.0
  geocoding: ^2.2.1
  url_launcher: ^6.3.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

  # Voice & AI
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1

  # Image handling
  image_picker: ^1.1.2
  photo_view: ^0.15.0

  # Social
  share_plus: ^10.0.2
  video_player: ^2.9.2

  # Offline & connectivity
  connectivity_plus: ^6.0.5

  # Reels/visibility
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Ensure these folders exist and contain the referenced files.
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/places/
    - assets/images/hotels/
    - assets/images/restaurants/
    - assets/images/users/
    - assets/images/trip_groups/
    - assets/images/airports/
    - assets/images/train_stations/
    - assets/images/bus_stops/
    - assets/images/landmarks/
    - assets/icons/
    - assets/icons/feather/
    - assets/icons/lucide/
    - assets/animations/
    - assets/seed-data/
    - assets/fonts/        # added so fonts are bundled on web
    - .env

  # Custom fonts (files must exist under assets/fonts/)
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
