name: naveeka
description: Naveeka - All-in-One Travel App with Inspiration, Planning, Booking, Chat, and AI Copilot in One Flow.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^3.0.1

  # HTTP & Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  http: ^1.2.2
  http_parser: ^4.0.2
  web_socket_channel: ^3.0.3

  # Environment variables loader
  flutter_dotenv: ^6.0.0

  # Local storage (secure & regular)
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Caching network images
  cached_network_image: ^3.3.1

  # Async animations & effects
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

  # Media playback & recording
  just_audio: ^0.10.5
  audio_waveforms: ^1.0.6

  # Lottie animations
  lottie: ^3.1.2

  # Routing
  go_router: ^16.2.4

  # Utility packages
  intl: ^0.20.2
  collection: ^1.18.0
  meta: ^1.17.0

  # Icons
  cupertino_icons: ^1.0.8

  # Charts
  fl_chart: ^1.1.1

  # Markdown rendering (flutter_markdown is discontinued, use markdown_widget instead)
  markdown_widget: ^2.3.2

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.3.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

  # Voice & AI
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  permission_handler: ^12.0.1

  # Image handling
  image_picker: ^1.1.2
  photo_view: ^0.15.0

  # Social features
  share_plus: ^12.0.0
  video_player: ^2.9.2

  # Offline & Caching
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/places/
    - assets/images/hotels/
    - assets/images/restaurants/
    - assets/images/users/
    - assets/images/trip_groups/
    - assets/images/airports/
    - assets/images/train_stations/
    - assets/images/bus_stops/
    - assets/images/landmarks/
    - assets/icons/
    - assets/icons/feather/
    - assets/icons/lucide/
    - assets/animations/
    - assets/audio/
    - assets/seed-data/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
