# analysis_options.yaml
# Static analysis and lint rules for the Naveeka Flutter app.

# Start from Flutter's recommended rules
include: package:flutter_lints/flutter.yaml

analyzer:
  # Exclude generated and build artifacts
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/generated/**
    - ios/Flutter/.last_build_id
    - ios/Runner/GeneratedPluginRegistrant.*
    - android/app/**/GeneratedPluginRegistrant.*
    - web/renderer/**
  # Stricter type checks for safer code
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  # Elevate/tune diagnostics
  errors:
    unused_import: warning
    dead_code: warning
    todo: info

linter:
  rules:
    # Pubspec hygiene
    sort_pub_dependencies: true

    # Consistency and readability
    prefer_single_quotes: true
    directives_ordering: true
    always_declare_return_types: true
    cascade_invocations: true

    # Const and immutability for Flutter UI perf
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true

    # Safer, predictable state
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_late: true
    unnecessary_nullable_for_final_variable_declarations: true

    # Flutter widget hygiene
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

    # Streams/resources hygiene
    cancel_subscriptions: true
    close_sinks: true

    # Pragmatic defaults for production apps
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    avoid_bool_literals_in_conditional_expressions: true
