name: naveeka
description: Naveeka - All-in-One Travel App with Inspiration, Planning, Booking, Chat, and AI Copilot in One Flow.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audio_waveforms: ^1.0.6
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dio: ^5.5.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_tts: ^4.0.2
  geocoding: ^2.2.1
  geolocator: ^11.0.0
  go_router: ^13.2.0
  google_maps_flutter: ^2.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  just_audio: ^0.9.39
  lottie: ^3.1.2
  meta: ^1.12.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.4.0
  share_plus: ^10.0.2
  shimmer: ^3.0.0
  speech_to_text: ^6.6.0
  url_launcher: ^6.3.0
  video_player: ^2.9.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # If using localization (ARB files), uncomment:
  # generate: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/places/
    - assets/images/hotels/
    - assets/images/restaurants/
    - assets/images/users/
    - assets/images/trip_groups/
    - assets/images/airports/
    - assets/images/train_stations/
    - assets/images/bus_stops/
    - assets/images/landmarks/
    - assets/icons/
    - assets/icons/feather/
    - assets/icons/lucide/
    - assets/animations/
    - assets/seed-data/
    - .env # flutter_dotenv config asset

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
